AWSTemplateFormatVersion: 2010-09-09
Description: Combine an EC2 with a Security Group  

Resources:
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.nano
      ImageId: ami-06ce3edf0cff21f07 # Amazon Linux 2 AMI in Ireland
      SecurityGroups:
        - !Ref SSHSecurityGroup
      Tags:
        - Key: Name
          Value: "CF Generated simple EC2"
        - Key: Project
          Value: "CF"
        - Key: "GeneratedDescription"
          Value: !Join 
            - ""
            - - "EC2 Instance for "
              - !Ref AWS::Region

  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: "CF Generated simple SG"
        - Key: "GeneratedDescription"
          Value: !Join 
            - ""
            - - "SG for "
              - !Ref AWS::AccountId
