AWSTemplateFormatVersion: 2010-09-09
Description: EC2 instance with public DNS as an output

Resources:
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.nano
      ImageId: ami-06ce3edf0cff21f07 # Amazon Linux 2 AMI in Ireland
      Tags:
        - Key: Name
          Value: "CF Generated simple EC2"
        - Key: Project
          Value: "CF"

Outputs:
  InstanceDns:
    Value: !GetAtt
      - Ec2Instance
      - PublicDnsName