AWSTemplateFormatVersion: 2010-09-09
Description: S3 bucket with default encryption

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket 
    Properties:
      BucketName: cf-s3-bucket-pm
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256