AWSTemplateFormatVersion: 2010-09-09
Description: Simple NACL 


Resources:

  myVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16

  myNetworkAcl:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId: !Ref myVPC
        
  naclEntry:
    Type: AWS::EC2::NetworkAclEntry
    Properties: 
      CidrBlock: 10.0.1.0/24
      Egress: false
      NetworkAclId: !Ref myNetworkAcl
      PortRange: 
        From: 1024
        To: 65535
      Protocol: 6
      RuleAction: allow
      RuleNumber: 101